Add copyright headers and other boilerplate. tabnanny the files.

diff --git a/vdenv/HOWTO b/vdenv/HOWTO
--- a/vdenv/HOWTO
+++ b/vdenv/HOWTO
@@ -1,7 +1,14 @@
-#! /bin/bash -e
+#!/usr/bin/env bash
+# Copyright 2012 Canonical Ltd.  This software is licensed under the
+# GNU Affero General Public License version 3 (see the file LICENSE).
 #
 # This file documents how to get odev running on your system.  But it's also
 # a script; you may find that you can just run it and get a working setup.
+
+# Exit immediately if a command exits with a non-zero status.
+set -o errexit
+# Treat unset variables as an error when substituting.
+set -o nounset
 
 ## System-level setup.  This needs to be done only once.
 ./bin/system-setup
diff --git a/vdenv/bin/authorize-ssh b/vdenv/bin/authorize-ssh
--- a/vdenv/bin/authorize-ssh
+++ b/vdenv/bin/authorize-ssh
@@ -1,4 +1,6 @@
-#! /bin/bash -e
+#!/usr/bin/env bash
+# Copyright 2012 Canonical Ltd.  This software is licensed under the
+# GNU Affero General Public License version 3 (see the file LICENSE).
 #
 # Wait for the virtual cobbler instance's ssh server to start up, and set up
 # passwordless login if desired.
@@ -14,26 +16,31 @@
 # cobbler instance.  If key-owner is an asterisk, import the local public ssh
 # keys from ~/.ssh/id_*.pub
 
+# Exit immediately if a command exits with a non-zero status.
+set -o errexit
+# Treat unset variables as an error when substituting.
+set -o nounset
+
 cobblerlogin=$1
 keyowner=$2
 
 if test -z "$keyowner"
 then
-	echo "Not setting up ssh keys."
-	echo "I'll still test a login to Cobbler though."
-	inputfiles=/dev/null
-	remotecmd="uptime"
+    echo "Not setting up ssh keys."
+    echo "I'll still test a login to Cobbler though."
+    inputfiles=/dev/null
+    remotecmd="uptime"
 elif test "$keyowner" = "*"
 then
-	inputfiles=`ls ~/.ssh/id_*.pub`
-	echo "Copying public key(s): $inputfiles"
-	remotecmd="tee .ssh/authorized_keys"
+    inputfiles=`ls ~/.ssh/id_*.pub`
+    echo "Copying public key(s): $inputfiles"
+    remotecmd="tee .ssh/authorized_keys"
 else
-	inputfiles=/dev/null
-	remotecmd="ssh-import-id $keyowner"
+    inputfiles=/dev/null
+    remotecmd="ssh-import-id $keyowner"
 fi
 
 while ! cat $inputfiles | ssh $cobblerlogin -o StrictHostKeyChecking=no $remotecmd
 do
-	sleep 5
+    sleep 5
 done
diff --git a/vdenv/bin/start-odev b/vdenv/bin/start-odev
--- a/vdenv/bin/start-odev
+++ b/vdenv/bin/start-odev
@@ -1,6 +1,13 @@
-#! /bin/bash -e
-#
+#!/usr/bin/env bash
+# Copyright 2012 Canonical Ltd.  This software is licensed under the
+# GNU Affero General Public License version 3 (see the file LICENSE).
+
 # Get zimmer and cobbler running, assuming that zimmer has already been set up.
+
+# Exit immediately if a command exits with a non-zero status.
+set -o errexit
+# Treat unset variables as an error when substituting.
+set -o nounset
 
 ## create libvirt xml files for nodes, zimmer, network
 ./setup.py libvirt-setup
diff --git a/vdenv/bin/system-setup b/vdenv/bin/system-setup
--- a/vdenv/bin/system-setup
+++ b/vdenv/bin/system-setup
@@ -1,6 +1,14 @@
-#! /bin/bash -e
+#!/usr/bin/env bash
+# Copyright 2012 Canonical Ltd.  This software is licensed under the
+# GNU Affero General Public License version 3 (see the file LICENSE).
+
 #
 # System-wide setup for odev.  This requires sudo.
+
+# Exit immediately if a command exits with a non-zero status.
+set -o errexit
+# Treat unset variables as an error when substituting.
+set -o nounset
 
 ## install some dependencies
 pkgs=""
@@ -12,24 +20,24 @@ pkgs="$pkgs qemu-utils qemu-kvm" # needed generally
 
 new_pkgs=""
 for pkg in ${pkgs}; do
-	dpkg-query --show "$pkg" >/dev/null ||
-		new_pkgs="${new_pkgs:+${new_pkgs} }${pkg}"
+    dpkg-query --show "$pkg" >/dev/null ||
+        new_pkgs="${new_pkgs:+${new_pkgs} }${pkg}"
 done
 
 if [ -n "$new_pkgs" ]; then
-	sudo apt-get update -qq || /bin/true
-	sudo apt-get install -y $pkgs </dev/null
+    sudo apt-get update -qq || /bin/true
+    sudo apt-get install -y $pkgs </dev/null
 fi
 
 new_groups=""
 for group in libvirtd kvm; do
-	groups $USER | grep -q $group && continue
-	sudo adduser $USER $group
-	new_groups="${new_groups:+${new_groups} }${group}"
+    groups $USER | grep -q $group && continue
+    sudo adduser $USER $group
+    new_groups="${new_groups:+${new_groups} }${group}"
 done
 
 if [ -n "$new_groups" ]; then
-	cat <<EOF
+    cat <<EOF
 Done.
 
 The script just added you to the system group[s] $new_groups
@@ -38,7 +46,7 @@ If you were not previously in these groups, you will need to log out and
 log back in again to make the changes take effect.
 EOF
 
-	# The user may need to log out at this point.
-	echo "Ctrl-C if you want to log out now.  Otherwise, press <enter>."
-	read
+    # The user may need to log out at this point.
+    echo "Ctrl-C if you want to log out now.  Otherwise, press <enter>."
+    read
 fi
diff --git a/vdenv/bin/virsh-listener b/vdenv/bin/virsh-listener
--- a/vdenv/bin/virsh-listener
+++ b/vdenv/bin/virsh-listener
@@ -1,4 +1,6 @@
-#!/bin/bash -e
+#!/usr/bin/env bash
+# Copyright 2012 Canonical Ltd.  This software is licensed under the
+# GNU Affero General Public License version 3 (see the file LICENSE).
 
 ## * libvirt from the cobbler system:
 ##   after 'cobbler-setup' above is done, the cobbler system will know about
@@ -9,6 +11,11 @@
 ##   This can be done moderately securely with 'socat'.  Below, we tell socat
 ##   to forward tcp connections on 192.168.123.1:65001 to the libvirt unix
 ##   socket .  It restricts connections to zimmer's IP address.
+
+# Exit immediately if a command exits with a non-zero status.
+set -o errexit
+# Treat unset variables as an error when substituting.
+set -o nounset
 
 sock="/var/run/libvirt/libvirt-sock"
 
